[phases.setup]
nixPkgs = [
  "chromium",
  "glib",
  "nss",
  "nspr",
  "at-spi2-atk",
  "cups",
  "dbus",
  "expat",
  "libdrm",
  "mesa",
  "libgbm",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "xorg.libXcursor",
  "xorg.libXi",
  "xorg.libXtst",
  "xorg.libxshmfence",
  "pango",
  "cairo",
  "alsa-lib",
  "atk"
]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx playwright install chromium"]

[start]
cmd = "node src/server.js"
